server:
  port: 5020


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/booking_db
    username: root
    password: Viber+1014
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: booking-service-group

