server:
  port: 5006

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: seat-service-group

  datasource:
    url: jdbc:mysql://localhost:3306/airline_seat_db
    username: root
    password: Viber+1014

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true



