server:
  port: 5001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airline_user_db
    username: root
    password: Viber+1014
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
